"""empty message

Revision ID: 19dc4be0943a
Revises: 51d359f59399
Create Date: 2019-11-26 21:58:33.923814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dc4be0943a'
down_revision = '51d359f59399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_request_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_request_token_secret', sa.String(length=64), nullable=True),
    sa.Column('oauth_token', sa.String(length=64), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authentication')
    # ### end Alembic commands ###
